#pragma once

EXTERN_C const CLSID CLSID_HapDecoder;
EXTERN_C const CLSID CLSID_LAVSplitterSource;
EXTERN_C const CLSID CLSID_RawSampleGrabber;

EXTERN_C const CLSID MEDIASUBTYPE_DXT1;
EXTERN_C const CLSID MEDIASUBTYPE_DXT5;
EXTERN_C const CLSID MEDIASUBTYPE_DXTY;
